name: Inventory
version: @VERSION@
description: Provide items to players
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/Inventory
main: edgruberman.bukkit.inventory.Main
commands:
  'inventory:withdraw':
    aliases: [withdraw, delivery.withdraw]
    description: Open delivery for self
    permission: inventory.withdraw
    usage: '§f-> §7Usage: §b/<command>'
  'inventory:edit':
    aliases: [delivery.edit]
    description: Add or remove items in delivery
    permission: inventory.edit
    usage: '§f-> §7Usage: §b/<command> §o<Player>§3[ §b§o<Reason>§3]'
  'inventory:empty':
    aliases: [delivery.empty]
    description: Remove all items from delivery
    permission: inventory.empty
    usage: '§f-> §7Usage: §b/<command> §o<Player>§3[ §b§o<Reason>§3]'
  'inventory:define':
    aliases: [kit.define]
    description: Create, edit, or delete a kit
    permission: inventory.define
    usage: '§f-> §7Usage: §b/<command> §o<Kit>'
  'inventory:kit':
    aliases: [kit]
    description: Issue or recall a kit
    permission: inventory.kit
    usage: '§f-> §7Usage: §b/<command> §o<Kit>§3[ §b§o<Player>§3[ §b§o<Quantity>§3[ §b§o<Reason>§3]]]'
  'inventory:delete':
    aliases: [kit.delete]
    description: Delete a kit
    permission: inventory.delete
    usage: '§f-> §7Usage: §b/<command> §o<Kit>'
  'inventory:reload':
    description: Reload Inventory plugin
    permission: inventory.reload
    usage: '§f-> §7Usage: §b/<command>'
permissions:
  inventory.admin:
    description: Can use all features
    default: op
    children:
      inventory.user: true
      inventory.edit: true
      inventory.empty: true
      inventory.define: true
      inventory.kit: true
      inventory.delete: true
      inventory.reload: true
  inventory.user:
    description: Can use basic features
    default: true
    children:
      inventory.withdraw: true
      inventory.withdraw.chest: true
  inventory.withdraw:
    description: Can open delivery for self using a chest item
    default: false
    children:
      inventory.withdraw.chest: true
  inventory.withdraw.chest:
    description: Can open delivery for self using a chest item
    default: false
  inventory.edit:
    description: Can use edit command
    default: false
  inventory.empty:
    description: Can use empty command
    default: false
  inventory.define:
    description: Can use define command
    default: false
  inventory.kit:
    description: Can use kit command
    default: false
  inventory.delete:
    description: Can use delete command
    default: false
  inventory.reload:
    description: Can use reload command
    default: false