name: ParcelService
version: @VERSION@
description: Provide and track items given to players
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/ParcelService
main: edgruberman.bukkit.parcelservice.Main
commands:
  'parcelservice:define':
    aliases: [mps.define]
    description: Create, edit, or delete a kit
    permission: parcelservice.define
    usage: '§f-> §7Usage: §b/<command> §o<Kit>'
  'parcelservice:kit':
    aliases: [mps.kit]
    description: Issue or recall a kit
    permission: parcelservice.kit
    usage: '§f-> §7Usage: §b/<command> <Kit>§3[ §b§o<Player>§3[ §b§o<Quantity>§3[ §b§o<Reason>§3]]]'
  'parcelservice:edit':
    aliases: [mps.edit]
    description: Modify inventory pallet
    permission: parcelservice.edit
    usage: '§f-> §7Usage: §b/<command> <Player>§3[ §b§o<Reason>§3]'
  'parcelservice:reload':
    description: Reload ParcelService plugin
    permission: parcelservice.reload
    usage: '§f-> §7Usage: §b/<command>'
permissions:
  parcelservice.admin:
    description: Can use all commands
    default: op
    children:
      parcelservice.user: true
      parcelservice.define: true
      parcelservice.kit: true
      parcelservice.edit: true
      parcelservice.reload: true
  parcelservice.user:
    description: Can use basic commands
    default: true
    children:
      parcelservice.open: true
  parcelservice.open:
    description: Can open pallet for self
    default: false
  parcelservice.define:
    description: Can use define command
    default: false
  parcelservice.kit:
    description: Can use kit command
    default: false
  parcelservice.edit:
    description: Can use edit command
    default: false
  parcelservice.reload:
    description: Can use reload command
    default: false