name: Deliver
version: @VERSION@
description: Provide items to players
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/Deliver
main: edgruberman.bukkit.deliver.Main
commands:
  'deliver:edit':
    aliases: [deliver, deliver.edit]
    description: Modify player specific box inventory
    permission: deliver.edit
    usage: '§f-> §7Usage: §b/<command> §o<Player>§3[ §b§o<Reason>§3]'
  'deliver:define':
    aliases: [kit.define]
    description: Create, edit, or delete a kit
    permission: deliver.define
    usage: '§f-> §7Usage: §b/<command> §o<Kit>'
  'deliver:kit':
    aliases: [kit]
    description: Issue or recall a kit
    permission: deliver.kit
    usage: '§f-> §7Usage: §b/<command> §o<Kit>§3[ §b§o<Player>§3[ §b§o<Quantity>§3[ §b§o<Reason>§3]]]'
  'deliver:delete':
    aliases: [kit.delete]
    description: Delete a kit from command line (no GUI)
    permission: deliver.delete
    usage: '§f-> §7Usage: §b/<command> §o<Kit>'
  'deliver:reload':
    description: Reload Deliver plugin
    permission: deliver.reload
    usage: '§f-> §7Usage: §b/<command>'
permissions:
  deliver.admin:
    description: Can use all commands
    default: op
    children:
      deliver.user: true
      deliver.define: true
      deliver.kit: true
      deliver.delete: true
      deliver.edit: true
      deliver.reload: true
  deliver.user:
    description: Can use basic commands
    default: true
    children:
      deliver.open: true
  deliver.open:
    description: Can open pallet for self
    default: false
  deliver.define:
    description: Can use define command
    default: false
  deliver.kit:
    description: Can use kit command
    default: false
  deliver.delete:
    description: Can use delete command
    default: false
  deliver.edit:
    description: Can use edit command
    default: false
  deliver.reload:
    description: Can use reload command
    default: false