name: ParcelService
version: @VERSION@
description: Queue and track items given to players
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.parcelservice.Main
commands:
  'parcelservice:take':
    aliases: [take, parcelservice.take]
    description: Receive a kit
    permission: parcelservice.take
    usage: /<command>[ <Kit>[ <Quantity>]]
  'parcelservice:show':
    aliases: ['take?', parcelservice.show]
    description: View available kits
    permission: parcelservice.show
    usage: /<command>
  'parcelservice:log':
    aliases: [parcelservice.log]
    description: View kit history
    permission: parcelservice.log
    usage: /<command>[ <Page>]
  'parcelservice:add':
    aliases: [parcelservice.add]
    description: Add or remove kits
    permission: parcelservice.add
    usage: /<command> <Kit> <Player> <Quantity>[ <Reason>]
  'parcelservice:reload':
    description: Reload ParcelService plugin
    permission: parcelservice.reload
    usage: /<command>
permissions:
  parcelservice.admin:
    description: Can use all commands
    default: op
    children:
      parcelservice.user: true
      parcelservice.add: true
      parcelservice.show.all: true
      parcelservice.log.all: true
      parcelservice.reload: true
  parcelservice.user:
    description: Can use basic commands
    default: true
    children:
      parcelservice.take: true
      parcelservice.show: true
      parcelservice.log: true
  parcelservice.take:
    description: Can use take command
    default: false
  parcelservice.show:
    description: Can use show command
    default: false
  parcelservice.log:
    description: Can use log command
    default: false
  parcelservice.add:
    description: Can use add command
    default: false
  parcelservice.reload:
    description: Can use reload command
    default: false
  parcelservice.show.all:
    description: Can use show command to view the balance for any player
    default: false
  parcelservice.log.all:
    description: Can use log command to view the log for any player
    default: false