name: Delivery
version: @VERSION@
description: Provide items to players
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/Delivery
main: edgruberman.bukkit.delivery.Main
commands:
  'delivery:edit':
    aliases: [delivery, delivery.edit]
    description: Modify player specific box inventory
    permission: delivery.edit
    usage: '§f-> §7Usage: §b/<command> <Player>§3[ §b§o<Reason>§3]'
  'delivery:define':
    aliases: [kit.define, delivery.define]
    description: Create, edit, or delete a kit
    permission: delivery.define
    usage: '§f-> §7Usage: §b/<command> §o<Kit>'
  'delivery:kit':
    aliases: [kit, delivery.kit]
    description: Issue or recall a kit
    permission: delivery.kit
    usage: '§f-> §7Usage: §b/<command> <Kit>§3[ §b§o<Player>§3[ §b§o<Quantity>§3[ §b§o<Reason>§3]]]'
  'delivery:reload':
    description: Reload Delivery plugin
    permission: delivery.reload
    usage: '§f-> §7Usage: §b/<command>'
permissions:
  delivery.admin:
    description: Can use all commands
    default: op
    children:
      delivery.user: true
      delivery.define: true
      delivery.kit: true
      delivery.edit: true
      delivery.reload: true
  delivery.user:
    description: Can use basic commands
    default: true
    children:
      delivery.open: true
  delivery.open:
    description: Can open pallet for self
    default: false
  delivery.define:
    description: Can use define command
    default: false
  delivery.kit:
    description: Can use kit command
    default: false
  delivery.edit:
    description: Can use edit command
    default: false
  delivery.reload:
    description: Can use reload command
    default: false